In [1]:
import math

In [2]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [3]:
math.sqrt(25)

5.0

In [4]:
math.pow(6,4)

1296.0

In [7]:
math.pi

3.141592653589793

In [8]:
math.gcd(9,19)

1

In [9]:
import random

In [10]:
dir(random)

['BPF',
 'LOG4',
 'NV_MAGICCONST',
 'RECIP_BPF',
 'Random',
 'SG_MAGICCONST',
 'SystemRandom',
 'TWOPI',
 '_Sequence',
 '_Set',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_accumulate',
 '_acos',
 '_bisect',
 '_ceil',
 '_cos',
 '_e',
 '_exp',
 '_floor',
 '_inst',
 '_log',
 '_os',
 '_pi',
 '_random',
 '_repeat',
 '_sha512',
 '_sin',
 '_sqrt',
 '_test',
 '_test_generator',
 '_urandom',
 '_warn',
 'betavariate',
 'choice',
 'choices',
 'expovariate',
 'gammavariate',
 'gauss',
 'getrandbits',
 'getstate',
 'lognormvariate',
 'normalvariate',
 'paretovariate',
 'randbytes',
 'randint',
 'random',
 'randrange',
 'sample',
 'seed',
 'setstate',
 'shuffle',
 'triangular',
 'uniform',
 'vonmisesvariate',
 'weibullvariate']

#### Numpy
- One of the most efficient modules of data science used for scientific computation
- Numpy stands for NumericalPython
- numpy is the module 
- we can gather/collect the data and arranged in array format


In [11]:
import numpy as np

In [13]:
np.__version__ # version of numpy module

'1.21.5'

#### array()
- we will arrange in array format
- matrix format
- array is the sub module of numpy
- np.array(ele)
- array is immutable
- homogenous data structure

#### array()
- numpy.array(data)

In [16]:
# conversion of string into array
st=input("string:")
ar=np.array(st)
print(ar)

string:k a k i na da located at East
k a k i na da located at East


In [17]:
ar

array('k a k i na da located at East', dtype='<U29')

In [19]:
# conversion of range(values) into the array
rn=range(10)
print(np.array(rn))

[0 1 2 3 4 5 6 7 8 9]


In [23]:
rn=range(10,28)
print(np.array(rn)) # 1d array:row matrix

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]


In [24]:
print(np.array(range(10,40,5)))

[10 15 20 25 30 35]


In [25]:
# convert the tuple/list/set into array
tp=(1,3,'python',4,5,'hi','hey')
np.array(tp)

array(['1', '3', 'python', '4', '5', 'hi', 'hey'], dtype='<U11')

In [28]:
li=list(map(int,input().split()))
ar=np.array(li)
print(li) # list
print(ar) # nd array

90 65 34 78 23 9 4 6 7 12 
[90, 65, 34, 78, 23, 9, 4, 6, 7, 12]
[90 65 34 78 23  9  4  6  7 12]


In [29]:
# dict :paired @ 2d format
# array:1d

In [32]:
# set
s=set(li)
sar=np.array(s)
print(sar)

{65, 34, 4, 6, 7, 9, 12, 78, 23, 90}


In [33]:
type(sar)

numpy.ndarray

In [34]:
# Ndimensional matrix


In [35]:
# list of lists/tuples
mul=[[1,2],[3,4],[5,6]]
alr=np.array(mul)
print(alr) # 2d array:3x2

[[1 2]
 [3 4]
 [5 6]]


In [36]:
tps=([3,4,5],['a','e','h'])
print(np.array(tps))

[['3' '4' '5']
 ['a' 'e' 'h']]


In [37]:
# create 3x3 
mt=np.array([[9,12,34],[89,45,67],(9,34,15)],dtype='float')
mt

array([[ 9., 12., 34.],
       [89., 45., 67.],
       [ 9., 34., 15.]])

In [39]:
mt.ndim # to check the dimensions 

2

In [40]:
mt.dtype #data type of each item

dtype('float64')

In [41]:
mt.itemsize # item size of each item

8

In [42]:
mt.shape # (rows,col)

(3, 3)

In [43]:
mt.size # total no.of elements

9

In [45]:
#### multi dimensional
#we can create 32 dimensional array using numpy

In [46]:
mt

array([[ 9., 12., 34.],
       [89., 45., 67.],
       [ 9., 34., 15.]])

In [52]:
new=np.array([1,2,3,4,5],ndmin=5,
             dtype='str')
print(new)

[[[[['1' '2' '3' '4' '5']]]]]


In [53]:
# identity matrix
# ones
# zeros
# full
# fill
# diag
# linspace

In [55]:
eye=np.eye((3)) # identity matrix
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
eye=np.eye((3),4) # identity matrix
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [60]:
# ones matrix
one=np.ones(3,dtype='int')
one

array([1, 1, 1])

In [62]:
# ones matrix
one=np.ones((3,3)) # ones matrix
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
# zeros matrix
z=np.zeros(3)
z

array([0., 0., 0.])

In [64]:
# zeros matrix
z=np.zeros((4,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
# full and fill
fl=np.full((3),'hi') # row with ele
fl

array(['hi', 'hi', 'hi'], dtype='<U2')

In [70]:
# full and fill
fl=np.full((4,3),5) # shape with ele
fl

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [79]:
fl.fill(9)

In [78]:
fl.fill('hi') # doesn't support

ValueError: invalid literal for int() with base 10: 'hi'

In [80]:
fl

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

##### arange()
- creates the ndimensional array with formal values starts from 0
- np.arange()

In [83]:
arn=np.arange(18) # works similar to range
print(arn)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [84]:
type(arn)

numpy.ndarray

In [85]:
print(np.arange(10,45))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44]


In [92]:
rn=np.arange(10,45,5)
rn.dtype='float'

ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.

In [94]:
ar.dtype='float'

In [95]:
ar

array([1.37929726e-312, 1.65515672e-312, 1.90979621e-313, 1.27319747e-313,
       2.54639495e-313])

In [89]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [90]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [96]:
# linspace 
# linear space among the interval

In [97]:
fl

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [104]:
for row in fl: # depends rows
    print(row) # be default

[9 9 9]
[9 9 9]
[9 9 9]
[9 9 9]


In [107]:
np.linspace(1,4) # 50 paritions 

array([1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
       1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
       1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
       1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
       2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
       2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
       2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
       3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
       3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
       3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ])

In [108]:
1,2,3,4 :50paritions

SyntaxError: only single target (not tuple) can be annotated (1148435196.py, line 1)

In [109]:
4/50

0.08

In [110]:
print(np.linspace(2,6,9))

[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6. ]


In [111]:
2,3,4,5,6:5/9

0.5555555555555556

#### reshape()
- reshapes the existed array
- reshape(row,col)

In [114]:
ln=np.linspace(5,10,12).reshape(3,4) # 50
print(ln)

[[ 5.          5.45454545  5.90909091  6.36363636]
 [ 6.81818182  7.27272727  7.72727273  8.18181818]
 [ 8.63636364  9.09090909  9.54545455 10.        ]]


In [115]:
n=np.arange(28).reshape(7,4)
print(n)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [116]:
432: values
    # pairs
    

SyntaxError: illegal target for annotation (3538150681.py, line 1)

In [121]:
kl=np.arange(432).reshape(18,-1) # unknown
print(kl)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23]
 [ 24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41
   42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
   66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
   90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113
  114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
  162 163 164 165 166 167]
 [168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185
  186 187 188 189 190 191]
 [192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209
  210 211 212 213 214 215]
 [216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
  234 235 236 237

In [122]:
print(np.arange(45).reshape(-1,9))

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]]


In [126]:
# 3d array
# 3 dimensions: (no.of arrays,rows,col)
xy=np.arange(45).reshape(3,5,3)
print(xy)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]]


In [124]:
xy[0] # first array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [127]:
xy[1]

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [132]:
xyz=np.array([[[1,2],[3,4]],[['a','e'],['o','p']]])
xyz
            

array([[['1', '2'],
        ['3', '4']],

       [['a', 'e'],
        ['o', 'p']]], dtype='<U11')

In [133]:
xyz.ndim

3

In [138]:
new=arn.reshape(6,3)
new

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [139]:
new[0]

array([0, 1, 2])

In [140]:
new[4] # 5th row

array([12, 13, 14])

In [141]:
new[3][1] # 2d indexing

10

In [142]:
# slicing
new[:4]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [144]:
new[2:4]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [146]:
 #alternate rows
new[::2]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [147]:
# columns
new[:,2]

array([ 2,  5,  8, 11, 14, 17])

In [150]:
new[2][1:] # 3rd row

array([7, 8])

In [152]:
new[:,1:]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14],
       [16, 17]])

In [153]:
# alternate col in alternate rows
new[::2,::2]

array([[ 0,  2],
       [ 6,  8],
       [12, 14]])

In [154]:
new

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

#### random
- generates the random values
- np.random()

#### np.random()
- np.random.randint(stop)
- np.random.randint(st,sp)
- np.random.randint(st,sp,stp)
- np.random.random()
- np.random.rand()
- np.random.randd()

In [164]:
print(np.random.randint(10))
# random digit in the range

9


In [173]:
np.random.randint(30,80)

48

In [176]:
np.random.randint(-9,10)

-4

In [178]:
np.random.randint(-100,-8)

-89

In [189]:
np.random.randint(-200,-17,1000).reshape(20,50)

array([[-187, -102, -130, -135, -162, -188, -143,  -30, -145, -182, -197,
         -84, -126, -117,  -85,  -56, -104, -158, -106,  -81, -186,  -67,
         -51, -186, -177, -127, -100, -135,  -62,  -28,  -97,  -50, -113,
        -175, -103, -125,  -59,  -99, -173, -186, -196, -186,  -75, -110,
         -40,  -48,  -65, -170,  -62,  -38],
       [ -54, -155,  -91,  -67,  -71,  -74,  -61,  -76,  -93,  -55, -179,
         -72,  -74,  -32, -162,  -29, -110, -122,  -68, -163,  -81, -190,
        -171,  -67,  -23,  -77,  -44, -124, -143,  -65,  -71, -117, -112,
         -48, -122,  -38,  -29, -140, -126, -155,  -34,  -98, -118,  -66,
        -133,  -90, -196,  -29, -165,  -72],
       [-130,  -63,  -61,  -48,  -94, -184, -189, -133,  -72, -117,  -56,
        -178,  -99, -146, -125, -151, -164,  -96, -139, -113,  -54, -162,
         -78, -118, -178,  -85,  -45,  -85,  -35,  -71,  -44, -137, -113,
         -43, -158,  -56, -166, -108, -117,  -83,  -67,  -43,  -19, -193,
         -63,  -81, -1

In [194]:
np.random.random((2,4)) 
# random floating values from 0 to 1

array([[0.50618066, 0.97112804, 0.31719632, 0.41618667],
       [0.17571035, 0.31956945, 0.17048444, 0.11626876]])

In [196]:
np.random.rand(3,5)

array([[0.17046624, 0.80722231, 0.40320374, 0.31411112, 0.43807618],
       [0.15753607, 0.24734579, 0.89780559, 0.80053978, 0.8391112 ],
       [0.38495957, 0.26365703, 0.64270531, 0.39680223, 0.0314634 ]])

In [203]:
np.random.randn(10,20)

array([[-7.49112435e-01, -4.99516928e-01,  1.23456944e-01,
        -2.93968242e-01, -1.70228889e+00,  5.73995477e-02,
        -2.10990130e+00, -1.20563041e+00,  5.21199008e-04,
         6.86004044e-01, -1.48335049e+00,  8.31895089e-02,
        -8.56505093e-01, -1.50780036e+00, -1.61699692e-02,
        -8.77016139e-01,  1.38031989e+00,  1.83160776e+00,
         2.21581537e-01,  7.07968925e-01],
       [-2.12111334e-01,  1.00820097e+00, -1.57587668e+00,
         1.92684809e-01, -7.66440300e-02,  9.05541444e-01,
         1.35552363e+00, -6.70440068e-02, -1.34139390e+00,
         1.33151355e+00,  1.16576508e+00,  2.94011928e-01,
         7.36522575e-01, -9.34573545e-01, -1.32962199e-01,
        -4.88293239e-01,  2.57597010e+00,  5.27571041e-01,
         1.07269643e+00, -1.07371558e+00],
       [-6.32143669e-01,  1.39596377e+00, -3.65451995e-01,
         1.34616966e-02, -9.91384485e-01, -8.64304203e-01,
        -9.01164181e-01,  3.04542594e-01,  2.80909005e-01,
        -1.37496114e+00,  1.0

In [204]:
# fancy indexing
new

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [214]:
knew=np.random.randint(100,500,25).reshape(5,-1)
print(knew)

[[244 201 400 402 211]
 [370 130 173 129 318]
 [390 360 134 202 224]
 [400 390 148 291 427]
 [266 173 485 337 362]]


In [220]:
# array whose values >340
knew[knew>320]

array([400, 402, 370, 390, 360, 400, 390, 427, 485, 337, 362])

##### broadcasting
- apply scalar quantity on arrays
- causes big difference

In [222]:
knew+19

array([[263, 220, 419, 421, 230],
       [389, 149, 192, 148, 337],
       [409, 379, 153, 221, 243],
       [419, 409, 167, 310, 446],
       [285, 192, 504, 356, 381]])

In [223]:
#### arithmetic operations
addition,subtraction

NameError: name 'addition' is not defined

In [224]:
fml=np.arange(100,125).reshape(5,5)
fml

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124]])

In [225]:
print("shiva")


shiva


In [227]:
num=int(input())
for dig in range(1,11):
    print(num,"x",dig,"=",num*dig)

8
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80


In [228]:
knew+fml

array([[344, 302, 502, 505, 315],
       [475, 236, 280, 237, 427],
       [500, 471, 246, 315, 338],
       [515, 506, 265, 409, 546],
       [386, 294, 607, 460, 486]])

In [229]:
knew-fml

array([[144, 100, 298, 299, 107],
       [265,  24,  66,  21, 209],
       [280, 249,  22,  89, 110],
       [285, 274,  31, 173, 308],
       [146,  52, 363, 214, 238]])

In [230]:
knew*fml

array([[24400, 20301, 40800, 41406, 21944],
       [38850, 13780, 18511, 13932, 34662],
       [42900, 39960, 15008, 22826, 25536],
       [46000, 45240, 17316, 34338, 50813],
       [31920, 20933, 59170, 41451, 44888]])

In [231]:
knew.transpose() # rows arranged as cols

array([[244, 370, 390, 400, 266],
       [201, 130, 360, 390, 173],
       [400, 173, 134, 148, 485],
       [402, 129, 202, 291, 337],
       [211, 318, 224, 427, 362]])

In [234]:
knew.dot(fml) # dot product (vectors)

array([[161055, 162513, 163971, 165429, 166887],
       [122675, 123795, 124915, 126035, 127155],
       [141650, 142960, 144270, 145580, 146890],
       [181935, 183591, 185247, 186903, 188559],
       [180310, 181933, 183556, 185179, 186802]])

In [237]:
knew.min() # minimum value of knew

129

In [239]:
knew.max()

485

In [240]:
knew.sum() # summation of all the values of knew

7167

In [241]:
knew.mean()

286.68

In [242]:
knew.std()

106.78828400157013

#### Scientific computation
- logarithms and exponentials

In [243]:
np.log(10)

2.302585092994046

In [244]:
np.log([1,2,3,4,10])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 2.30258509])

In [245]:
np.log(knew)

array([[5.49716823, 5.30330491, 5.99146455, 5.99645209, 5.35185813],
       [5.91350301, 4.86753445, 5.15329159, 4.8598124 , 5.76205138],
       [5.96614674, 5.88610403, 4.8978398 , 5.3082677 , 5.41164605],
       [5.99146455, 5.96614674, 4.99721227, 5.67332327, 6.05678401],
       [5.58349631, 5.15329159, 6.18414889, 5.82008293, 5.89164421]])

In [246]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [249]:
help(np.invert)

Help on ufunc:

invert = <ufunc 'invert'>
    invert(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Compute bit-wise inversion, or bit-wise NOT, element-wise.
    
    Computes the bit-wise NOT of the underlying binary representation of
    the integers in the input arrays. This ufunc implements the C/Python
    operator ``~``.
    
    For signed integer inputs, the two's complement is returned.  In a
    two's-complement system negative numbers are represented by the two's
    complement of the absolute value. This is the most common method of
    representing signed integers on computers [1]_. A N-bit
    two's-complement system can represent every integer in the range
    :math:`-2^{N-1}` to :math:`+2^{N-1}-1`.
    
    Parameters
    ----------
    x : array_like
        Only integer and boolean types are handled.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the r

In [250]:
np.invert(knew)

array([[-245, -202, -401, -403, -212],
       [-371, -131, -174, -130, -319],
       [-391, -361, -135, -203, -225],
       [-401, -391, -149, -292, -428],
       [-267, -174, -486, -338, -363]], dtype=int32)

In [251]:
knew

array([[244, 201, 400, 402, 211],
       [370, 130, 173, 129, 318],
       [390, 360, 134, 202, 224],
       [400, 390, 148, 291, 427],
       [266, 173, 485, 337, 362]])

In [252]:
np.exp(8)

2980.9579870417283

In [253]:
np.exp([8,3,4])

array([2980.95798704,   20.08553692,   54.59815003])

In [255]:
np.exp(fml)

array([[2.68811714e+43, 7.30705998e+43, 1.98626484e+44, 5.39922761e+44,
        1.46766223e+45],
       [3.98951957e+45, 1.08446386e+46, 2.94787839e+46, 8.01316426e+46,
        2.17820388e+47],
       [5.92097203e+47, 1.60948707e+48, 4.37503945e+48, 1.18925902e+49,
        3.23274119e+49],
       [8.78750164e+49, 2.38869060e+50, 6.49313426e+50, 1.76501689e+51,
        4.79781333e+51],
       [1.30418088e+52, 3.54513118e+52, 9.63666567e+52, 2.61951732e+53,
        7.12058633e+53]])

##### vectorized function
- takes a python func that returns the vectorized function which is used to speed up the python code without loop

In [256]:
def greater(a,b):
    if a>b:
        return a
    else:return b

In [259]:
greater(14,5)

14

In [258]:
greater(9,13)

13

In [260]:
greater([4,5,19],[10,8,4])

[10, 8, 4]

In [263]:
g=np.vectorize(greater)
g([43,5,61,19],[9,10,8,4])

array([43, 10, 61, 19])

In [267]:
x,y=[4,5,19],[10,8,4]
res=[]
for a,b in zip(x,y): # multiple iterables
    if a>b:
        res.append(a)
    else:
        res.append(b)
res

[10, 8, 19]

In [268]:
scipy and matplotlib

NameError: name 'scipy' is not defined

##### html
- hyper text markup language


<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
    <source src="movie.ogg" type="video/ogg">
  Your browser does not support the video tag.
</video>